package spotifybackup.storage;

import org.hibernate.service.spi.ServiceException;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import se.michaelthelin.spotify.model_objects.specification.Track;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.LogManager;

import static org.junit.jupiter.api.Assertions.*;

public class SpotifyTrackRepositoryTest {
    static private SpotifyTrackRepository spotifyTrackRepository;

    @BeforeAll
    static void setup() {
        LogManager.getLogManager().getLogger("").setLevel(Level.WARNING);
        final Properties DB_ACCESS = new Properties();
        DB_ACCESS.put("hibernate.hikari.dataSource.url", "jdbc:h2:./build/test;DB_CLOSE_DELAY=-1");
        DB_ACCESS.put("hibernate.hbm2ddl.auto", "create");
        DB_ACCESS.put("hibernate.show_sql", "false");
        DB_ACCESS.put("persistenceUnitName", "testdb");
        try {
            spotifyTrackRepository = new SpotifyTrackRepository(DB_ACCESS);
        } catch (ServiceException e) {
            throw new RuntimeException("Can't create db access service, is db version out of date?\n" + e.getMessage());
        }
    }

    @Test
    void ensure_track_can_be_persisted() {
        // Arrange
        final Track apiTrack = new Track.JsonUtil().createModelObject("""
                {
                  "album": {
                    "album_type": "compilation",
                    "artists": [
                      {
                        "external_urls": {
                          "spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
                        },
                        "href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                        "id": "0LyfQWJT6nXafLPZqxe9Of",
                        "name": "Various Artists",
                        "type": "artist",
                        "uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
                      }
                    ],
                    "available_markets": [
                      "AD",
                      "AE",
                      "AG",
                      "AL",
                      "AM",
                      "AO",
                      "AR",
                      "AT",
                      "AU",
                      "AZ",
                      "BA",
                      "BB",
                      "BD",
                      "BE",
                      "BF",
                      "BG",
                      "BH",
                      "BI",
                      "BJ",
                      "BN",
                      "BO",
                      "BR",
                      "BS",
                      "BT",
                      "BW",
                      "BY",
                      "BZ",
                      "CA",
                      "CD",
                      "CG",
                      "CH",
                      "CI",
                      "CL",
                      "CM",
                      "CO",
                      "CR",
                      "CV",
                      "CW",
                      "CY",
                      "CZ",
                      "DE",
                      "DJ",
                      "DK",
                      "DM",
                      "DO",
                      "DZ",
                      "EC",
                      "EE",
                      "EG",
                      "ES",
                      "ET",
                      "FI",
                      "FJ",
                      "FM",
                      "FR",
                      "GA",
                      "GB",
                      "GD",
                      "GE",
                      "GH",
                      "GM",
                      "GN",
                      "GQ",
                      "GR",
                      "GT",
                      "GW",
                      "GY",
                      "HK",
                      "HN",
                      "HR",
                      "HT",
                      "HU",
                      "ID",
                      "IE",
                      "IL",
                      "IN",
                      "IQ",
                      "IS",
                      "IT",
                      "JM",
                      "JO",
                      "JP",
                      "KE",
                      "KG",
                      "KH",
                      "KI",
                      "KM",
                      "KN",
                      "KR",
                      "KW",
                      "KZ",
                      "LA",
                      "LB",
                      "LC",
                      "LI",
                      "LK",
                      "LR",
                      "LS",
                      "LT",
                      "LU",
                      "LV",
                      "LY",
                      "MA",
                      "MC",
                      "MD",
                      "ME",
                      "MG",
                      "MH",
                      "MK",
                      "ML",
                      "MN",
                      "MO",
                      "MR",
                      "MT",
                      "MU",
                      "MV",
                      "MW",
                      "MX",
                      "MY",
                      "MZ",
                      "NA",
                      "NE",
                      "NG",
                      "NI",
                      "NL",
                      "NO",
                      "NP",
                      "NR",
                      "NZ",
                      "OM",
                      "PA",
                      "PE",
                      "PG",
                      "PH",
                      "PK",
                      "PL",
                      "PS",
                      "PT",
                      "PW",
                      "PY",
                      "QA",
                      "RO",
                      "RS",
                      "RW",
                      "SA",
                      "SB",
                      "SC",
                      "SE",
                      "SG",
                      "SI",
                      "SK",
                      "SL",
                      "SM",
                      "SN",
                      "SR",
                      "ST",
                      "SV",
                      "SZ",
                      "TD",
                      "TG",
                      "TH",
                      "TJ",
                      "TL",
                      "TN",
                      "TO",
                      "TR",
                      "TT",
                      "TV",
                      "TW",
                      "TZ",
                      "UA",
                      "UG",
                      "US",
                      "UY",
                      "UZ",
                      "VC",
                      "VE",
                      "VN",
                      "VU",
                      "WS",
                      "XK",
                      "ZA",
                      "ZM",
                      "ZW"
                    ],
                    "external_urls": {
                      "spotify": "https://open.spotify.com/album/1NwyvfpB5V9cYEoH5GsWpg"
                    },
                    "href": "https://api.spotify.com/v1/albums/1NwyvfpB5V9cYEoH5GsWpg",
                    "id": "1NwyvfpB5V9cYEoH5GsWpg",
                    "images": [
                      {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b2738ffd591babce4e1ddd214133",
                        "width": 640
                      },
                      {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e028ffd591babce4e1ddd214133",
                        "width": 300
                      },
                      {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d000048518ffd591babce4e1ddd214133",
                        "width": 64
                      }
                    ],
                    "name": "Rain World (Selections from the Original Game Soundtrack)",
                    "release_date": "2017-05-12",
                    "release_date_precision": "day",
                    "total_tracks": 40,
                    "type": "album",
                    "uri": "spotify:album:1NwyvfpB5V9cYEoH5GsWpg"
                  },
                  "artists": [
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/15l4YWi3MSO3iVKwmRPdN1"
                      },
                      "href": "https://api.spotify.com/v1/artists/15l4YWi3MSO3iVKwmRPdN1",
                      "id": "15l4YWi3MSO3iVKwmRPdN1",
                      "name": "Lydia Esrig",
                      "type": "artist",
                      "uri": "spotify:artist:15l4YWi3MSO3iVKwmRPdN1"
                    },
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3hnNFBVerLqoj6p252UniW"
                      },
                      "href": "https://api.spotify.com/v1/artists/3hnNFBVerLqoj6p252UniW",
                      "id": "3hnNFBVerLqoj6p252UniW",
                      "name": "James Primate",
                      "type": "artist",
                      "uri": "spotify:artist:3hnNFBVerLqoj6p252UniW"
                    }
                  ],
                  "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK"
                  ],
                  "disc_number": 1,
                  "duration_ms": 146000,
                  "explicit": false,
                  "external_ids": {
                    "isrc": "DEVF41700251"
                  },
                  "external_urls": {
                    "spotify": "https://open.spotify.com/track/5ChJ4hWOAthUuqAqnEi4vf"
                  },
                  "href": "https://api.spotify.com/v1/tracks/5ChJ4hWOAthUuqAqnEi4vf",
                  "id": "5ChJ4hWOAthUuqAqnEi4vf",
                  "is_local": false,
                  "name": "Bio-Engineering",
                  "popularity": 36,
                  "preview_url": "https://p.scdn.co/mp3-preview/837c3d69b475d4448e0be613f41e31a8d1b41b6f?cid=cc9a3c5ed3954a348dab315f959acdcc",
                  "track_number": 6,
                  "type": "track",
                  "uri": "spotify:track:5ChJ4hWOAthUuqAqnEi4vf"
                }
                """);
        assertFalse(spotifyTrackRepository.exists(apiTrack),
                "Track with Spotify ID " + apiTrack.getId() + " shouldn't already exist.");

        // Act
        var persistedTrack = spotifyTrackRepository.persist(apiTrack);

        // Assert
        assertTrue(spotifyTrackRepository.exists(apiTrack.getId()), "Can't find Artist by Spotify ID.");
        assertTrue(spotifyTrackRepository.exists(apiTrack), "Can't find Artist by apiArtist/Spotify ID.");
        assertTrue(spotifyTrackRepository.exists(persistedTrack), "Can't find Artist by Object reference.");
        assertEquals(apiTrack.getArtists().length, persistedTrack.getSpotifyArtists().size());
        assertEquals(apiTrack.getAlbum().getId(), persistedTrack.getSpotifyAlbum().getSpotifyID().getId());
    }


    @Test
    void ensure_multiple_tracks_can_be_persisted() {
        // Arrange
        final long oldCount = spotifyTrackRepository.count();
        final Track[] apiTracks = {new Track.JsonUtil().createModelObject("""
                {
                  "album": {
                    "album_type": "album",
                    "artists": [
                      {
                        "external_urls": {
                          "spotify": "https://open.spotify.com/artist/5BcAKTbp20cv7tC5VqPFoC"
                        },
                        "href": "https://api.spotify.com/v1/artists/5BcAKTbp20cv7tC5VqPFoC",
                        "id": "5BcAKTbp20cv7tC5VqPFoC",
                        "name": "Macklemore & Ryan Lewis",
                        "type": "artist",
                        "uri": "spotify:artist:5BcAKTbp20cv7tC5VqPFoC"
                      },
                      {
                        "external_urls": {
                          "spotify": "https://open.spotify.com/artist/3JhNCzhSMTxs9WLGJJxWOY"
                        },
                        "href": "https://api.spotify.com/v1/artists/3JhNCzhSMTxs9WLGJJxWOY",
                        "id": "3JhNCzhSMTxs9WLGJJxWOY",
                        "name": "Macklemore",
                        "type": "artist",
                        "uri": "spotify:artist:3JhNCzhSMTxs9WLGJJxWOY"
                      },
                      {
                        "external_urls": {
                          "spotify": "https://open.spotify.com/artist/4myTppRgh0rojLxx8RycOp"
                        },
                        "href": "https://api.spotify.com/v1/artists/4myTppRgh0rojLxx8RycOp",
                        "id": "4myTppRgh0rojLxx8RycOp",
                        "name": "Ryan Lewis",
                        "type": "artist",
                        "uri": "spotify:artist:4myTppRgh0rojLxx8RycOp"
                      }
                    ],
                    "available_markets": [
                      "AD",
                      "AE",
                      "AG",
                      "AL",
                      "AM",
                      "AO",
                      "AR",
                      "AT",
                      "AU",
                      "AZ",
                      "BA",
                      "BB",
                      "BD",
                      "BE",
                      "BF",
                      "BG",
                      "BH",
                      "BI",
                      "BJ",
                      "BN",
                      "BO",
                      "BR",
                      "BS",
                      "BT",
                      "BW",
                      "BY",
                      "BZ",
                      "CA",
                      "CD",
                      "CG",
                      "CI",
                      "CL",
                      "CM",
                      "CO",
                      "CR",
                      "CV",
                      "CW",
                      "CY",
                      "CZ",
                      "DE",
                      "DJ",
                      "DK",
                      "DM",
                      "DO",
                      "DZ",
                      "EC",
                      "EE",
                      "EG",
                      "ES",
                      "ET",
                      "FI",
                      "FJ",
                      "FM",
                      "GA",
                      "GB",
                      "GD",
                      "GE",
                      "GH",
                      "GM",
                      "GN",
                      "GQ",
                      "GR",
                      "GT",
                      "GW",
                      "GY",
                      "HK",
                      "HN",
                      "HR",
                      "HT",
                      "HU",
                      "ID",
                      "IE",
                      "IL",
                      "IN",
                      "IQ",
                      "IS",
                      "JM",
                      "JO",
                      "JP",
                      "KE",
                      "KG",
                      "KH",
                      "KI",
                      "KM",
                      "KN",
                      "KR",
                      "KW",
                      "KZ",
                      "LA",
                      "LB",
                      "LC",
                      "LI",
                      "LK",
                      "LR",
                      "LS",
                      "LT",
                      "LU",
                      "LV",
                      "LY",
                      "MA",
                      "MC",
                      "MD",
                      "ME",
                      "MG",
                      "MH",
                      "MK",
                      "ML",
                      "MN",
                      "MO",
                      "MR",
                      "MT",
                      "MU",
                      "MV",
                      "MW",
                      "MX",
                      "MY",
                      "MZ",
                      "NA",
                      "NE",
                      "NG",
                      "NI",
                      "NL",
                      "NO",
                      "NP",
                      "NR",
                      "NZ",
                      "OM",
                      "PA",
                      "PE",
                      "PG",
                      "PH",
                      "PK",
                      "PL",
                      "PS",
                      "PT",
                      "PW",
                      "PY",
                      "QA",
                      "RO",
                      "RS",
                      "RW",
                      "SA",
                      "SB",
                      "SC",
                      "SE",
                      "SG",
                      "SI",
                      "SK",
                      "SL",
                      "SM",
                      "SN",
                      "SR",
                      "ST",
                      "SV",
                      "SZ",
                      "TD",
                      "TG",
                      "TH",
                      "TJ",
                      "TL",
                      "TN",
                      "TO",
                      "TR",
                      "TT",
                      "TV",
                      "TW",
                      "TZ",
                      "UA",
                      "UG",
                      "US",
                      "UY",
                      "UZ",
                      "VC",
                      "VE",
                      "VN",
                      "VU",
                      "WS",
                      "XK",
                      "ZA",
                      "ZM",
                      "ZW"
                    ],
                    "external_urls": {
                      "spotify": "https://open.spotify.com/album/76FXHQhTuT4QMIxfL09gX8"
                    },
                    "href": "https://api.spotify.com/v1/albums/76FXHQhTuT4QMIxfL09gX8",
                    "id": "76FXHQhTuT4QMIxfL09gX8",
                    "images": [
                      {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b27398a02fef3a8b1d80a0f164ec",
                        "width": 640
                      },
                      {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e0298a02fef3a8b1d80a0f164ec",
                        "width": 300
                      },
                      {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d0000485198a02fef3a8b1d80a0f164ec",
                        "width": 64
                      }
                    ],
                    "name": "The Heist",
                    "release_date": "2012-10-09",
                    "release_date_precision": "day",
                    "total_tracks": 15,
                    "type": "album",
                    "uri": "spotify:album:76FXHQhTuT4QMIxfL09gX8"
                  },
                  "artists": [
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/5BcAKTbp20cv7tC5VqPFoC"
                      },
                      "href": "https://api.spotify.com/v1/artists/5BcAKTbp20cv7tC5VqPFoC",
                      "id": "5BcAKTbp20cv7tC5VqPFoC",
                      "name": "Macklemore & Ryan Lewis",
                      "type": "artist",
                      "uri": "spotify:artist:5BcAKTbp20cv7tC5VqPFoC"
                    },
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3JhNCzhSMTxs9WLGJJxWOY"
                      },
                      "href": "https://api.spotify.com/v1/artists/3JhNCzhSMTxs9WLGJJxWOY",
                      "id": "3JhNCzhSMTxs9WLGJJxWOY",
                      "name": "Macklemore",
                      "type": "artist",
                      "uri": "spotify:artist:3JhNCzhSMTxs9WLGJJxWOY"
                    },
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4myTppRgh0rojLxx8RycOp"
                      },
                      "href": "https://api.spotify.com/v1/artists/4myTppRgh0rojLxx8RycOp",
                      "id": "4myTppRgh0rojLxx8RycOp",
                      "name": "Ryan Lewis",
                      "type": "artist",
                      "uri": "spotify:artist:4myTppRgh0rojLxx8RycOp"
                    },
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4e0nWw2r4BoQSKPQ2zpU13"
                      },
                      "href": "https://api.spotify.com/v1/artists/4e0nWw2r4BoQSKPQ2zpU13",
                      "id": "4e0nWw2r4BoQSKPQ2zpU13",
                      "name": "Ray Dalton",
                      "type": "artist",
                      "uri": "spotify:artist:4e0nWw2r4BoQSKPQ2zpU13"
                    }
                  ],
                  "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK"
                  ],
                  "disc_number": 1,
                  "duration_ms": 258342,
                  "explicit": false,
                  "external_ids": {
                    "isrc": "GMM881200021"
                  },
                  "external_urls": {
                    "spotify": "https://open.spotify.com/track/3bidbhpOYeV4knp8AIu8Xn"
                  },
                  "href": "https://api.spotify.com/v1/tracks/3bidbhpOYeV4knp8AIu8Xn",
                  "id": "3bidbhpOYeV4knp8AIu8Xn",
                  "is_local": false,
                  "name": "Can't Hold Us (feat. Ray Dalton)",
                  "popularity": 83,
                  "preview_url": "https://p.scdn.co/mp3-preview/989bcb16f82e4cfcbfebdf8cf0dd91abe86c84d1?cid=cc9a3c5ed3954a348dab315f959acdcc",
                  "track_number": 2,
                  "type": "track",
                  "uri": "spotify:track:3bidbhpOYeV4knp8AIu8Xn"
                }
                """), new Track.JsonUtil().createModelObject("""
                {
                  "album": {
                    "album_type": "album",
                    "artists": [
                      {
                        "external_urls": {
                          "spotify": "https://open.spotify.com/artist/5BcAKTbp20cv7tC5VqPFoC"
                        },
                        "href": "https://api.spotify.com/v1/artists/5BcAKTbp20cv7tC5VqPFoC",
                        "id": "5BcAKTbp20cv7tC5VqPFoC",
                        "name": "Macklemore & Ryan Lewis",
                        "type": "artist",
                        "uri": "spotify:artist:5BcAKTbp20cv7tC5VqPFoC"
                      },
                      {
                        "external_urls": {
                          "spotify": "https://open.spotify.com/artist/3JhNCzhSMTxs9WLGJJxWOY"
                        },
                        "href": "https://api.spotify.com/v1/artists/3JhNCzhSMTxs9WLGJJxWOY",
                        "id": "3JhNCzhSMTxs9WLGJJxWOY",
                        "name": "Macklemore",
                        "type": "artist",
                        "uri": "spotify:artist:3JhNCzhSMTxs9WLGJJxWOY"
                      },
                      {
                        "external_urls": {
                          "spotify": "https://open.spotify.com/artist/4myTppRgh0rojLxx8RycOp"
                        },
                        "href": "https://api.spotify.com/v1/artists/4myTppRgh0rojLxx8RycOp",
                        "id": "4myTppRgh0rojLxx8RycOp",
                        "name": "Ryan Lewis",
                        "type": "artist",
                        "uri": "spotify:artist:4myTppRgh0rojLxx8RycOp"
                      }
                    ],
                    "available_markets": [
                      "AD",
                      "AE",
                      "AG",
                      "AL",
                      "AM",
                      "AO",
                      "AR",
                      "AT",
                      "AU",
                      "AZ",
                      "BA",
                      "BB",
                      "BD",
                      "BE",
                      "BF",
                      "BG",
                      "BH",
                      "BI",
                      "BJ",
                      "BN",
                      "BO",
                      "BR",
                      "BS",
                      "BT",
                      "BW",
                      "BY",
                      "BZ",
                      "CA",
                      "CD",
                      "CG",
                      "CI",
                      "CL",
                      "CM",
                      "CO",
                      "CR",
                      "CV",
                      "CW",
                      "CY",
                      "CZ",
                      "DE",
                      "DJ",
                      "DK",
                      "DM",
                      "DO",
                      "DZ",
                      "EC",
                      "EE",
                      "EG",
                      "ES",
                      "ET",
                      "FI",
                      "FJ",
                      "FM",
                      "GA",
                      "GB",
                      "GD",
                      "GE",
                      "GH",
                      "GM",
                      "GN",
                      "GQ",
                      "GR",
                      "GT",
                      "GW",
                      "GY",
                      "HK",
                      "HN",
                      "HR",
                      "HT",
                      "HU",
                      "ID",
                      "IE",
                      "IL",
                      "IN",
                      "IQ",
                      "IS",
                      "JM",
                      "JO",
                      "JP",
                      "KE",
                      "KG",
                      "KH",
                      "KI",
                      "KM",
                      "KN",
                      "KR",
                      "KW",
                      "KZ",
                      "LA",
                      "LB",
                      "LC",
                      "LI",
                      "LK",
                      "LR",
                      "LS",
                      "LT",
                      "LU",
                      "LV",
                      "LY",
                      "MA",
                      "MC",
                      "MD",
                      "ME",
                      "MG",
                      "MH",
                      "MK",
                      "ML",
                      "MN",
                      "MO",
                      "MR",
                      "MT",
                      "MU",
                      "MV",
                      "MW",
                      "MX",
                      "MY",
                      "MZ",
                      "NA",
                      "NE",
                      "NG",
                      "NI",
                      "NL",
                      "NO",
                      "NP",
                      "NR",
                      "NZ",
                      "OM",
                      "PA",
                      "PE",
                      "PG",
                      "PH",
                      "PK",
                      "PL",
                      "PS",
                      "PT",
                      "PW",
                      "PY",
                      "QA",
                      "RO",
                      "RS",
                      "RW",
                      "SA",
                      "SB",
                      "SC",
                      "SE",
                      "SG",
                      "SI",
                      "SK",
                      "SL",
                      "SM",
                      "SN",
                      "SR",
                      "ST",
                      "SV",
                      "SZ",
                      "TD",
                      "TG",
                      "TH",
                      "TJ",
                      "TL",
                      "TN",
                      "TO",
                      "TR",
                      "TT",
                      "TV",
                      "TW",
                      "TZ",
                      "UA",
                      "UG",
                      "US",
                      "UY",
                      "UZ",
                      "VC",
                      "VE",
                      "VN",
                      "VU",
                      "WS",
                      "XK",
                      "ZA",
                      "ZM",
                      "ZW"
                    ],
                    "external_urls": {
                      "spotify": "https://open.spotify.com/album/76FXHQhTuT4QMIxfL09gX8"
                    },
                    "href": "https://api.spotify.com/v1/albums/76FXHQhTuT4QMIxfL09gX8",
                    "id": "76FXHQhTuT4QMIxfL09gX8",
                    "images": [
                      {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b27398a02fef3a8b1d80a0f164ec",
                        "width": 640
                      },
                      {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e0298a02fef3a8b1d80a0f164ec",
                        "width": 300
                      },
                      {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d0000485198a02fef3a8b1d80a0f164ec",
                        "width": 64
                      }
                    ],
                    "name": "The Heist",
                    "release_date": "2012-10-09",
                    "release_date_precision": "day",
                    "total_tracks": 15,
                    "type": "album",
                    "uri": "spotify:album:76FXHQhTuT4QMIxfL09gX8"
                  },
                  "artists": [
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/5BcAKTbp20cv7tC5VqPFoC"
                      },
                      "href": "https://api.spotify.com/v1/artists/5BcAKTbp20cv7tC5VqPFoC",
                      "id": "5BcAKTbp20cv7tC5VqPFoC",
                      "name": "Macklemore & Ryan Lewis",
                      "type": "artist",
                      "uri": "spotify:artist:5BcAKTbp20cv7tC5VqPFoC"
                    },
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3JhNCzhSMTxs9WLGJJxWOY"
                      },
                      "href": "https://api.spotify.com/v1/artists/3JhNCzhSMTxs9WLGJJxWOY",
                      "id": "3JhNCzhSMTxs9WLGJJxWOY",
                      "name": "Macklemore",
                      "type": "artist",
                      "uri": "spotify:artist:3JhNCzhSMTxs9WLGJJxWOY"
                    },
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4myTppRgh0rojLxx8RycOp"
                      },
                      "href": "https://api.spotify.com/v1/artists/4myTppRgh0rojLxx8RycOp",
                      "id": "4myTppRgh0rojLxx8RycOp",
                      "name": "Ryan Lewis",
                      "type": "artist",
                      "uri": "spotify:artist:4myTppRgh0rojLxx8RycOp"
                    },
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/56xTxG4nQMAs1GW9kvn0uA"
                      },
                      "href": "https://api.spotify.com/v1/artists/56xTxG4nQMAs1GW9kvn0uA",
                      "id": "56xTxG4nQMAs1GW9kvn0uA",
                      "name": "Wanz",
                      "type": "artist",
                      "uri": "spotify:artist:56xTxG4nQMAs1GW9kvn0uA"
                    }
                  ],
                  "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK"
                  ],
                  "disc_number": 1,
                  "duration_ms": 235982,
                  "explicit": false,
                  "external_ids": {
                    "isrc": "GMM881200022"
                  },
                  "external_urls": {
                    "spotify": "https://open.spotify.com/track/37rKwjBHaZurlyPYy3Nqvz"
                  },
                  "href": "https://api.spotify.com/v1/tracks/37rKwjBHaZurlyPYy3Nqvz",
                  "id": "37rKwjBHaZurlyPYy3Nqvz",
                  "is_local": false,
                  "name": "Thrift Shop (feat. Wanz)",
                  "popularity": 55,
                  "preview_url": "https://p.scdn.co/mp3-preview/1804ec4e74412d8b3efb67a929f21bc35dec5472?cid=cc9a3c5ed3954a348dab315f959acdcc",
                  "track_number": 3,
                  "type": "track",
                  "uri": "spotify:track:37rKwjBHaZurlyPYy3Nqvz"
                }
                """),
        };
        for (var apiTrack : apiTracks) {
            assertFalse(spotifyTrackRepository.exists(apiTrack),
                    "Track with Spotify ID " + apiTrack.getId() + " shouldn't already exist.");
        }

        // Act
        var persistedTracks = spotifyTrackRepository.persistAll(apiTracks);

        // Assert
        for (var apiTrack : apiTracks) {
            var persistedTrack = persistedTracks.stream()
                    .filter(t -> t.getSpotifyID().getId().equals(apiTrack.getId()))
                    .findAny();
            assertTrue(spotifyTrackRepository.exists(apiTrack.getId()), "Can't find Artist by Spotify ID.");
            assertTrue(spotifyTrackRepository.exists(apiTrack), "Can't find Artist by apiArtist/Spotify ID.");
            assertTrue(persistedTrack.isPresent());
            assertEquals(apiTrack.getArtists().length, persistedTrack.get().getSpotifyArtists().size());
            assertEquals(apiTrack.getAlbum().getId(), persistedTrack.get().getSpotifyAlbum().getSpotifyID().getId());
        }
        assertEquals(oldCount + apiTracks.length, spotifyTrackRepository.count());
    }
}
