package spotifybackup.storage;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.NoResultException;
import jakarta.persistence.Persistence;
import lombok.NonNull;
import se.michaelthelin.spotify.model_objects.specification.Image;

import java.util.*;

public class ArtistRepository {
    private final EntityManagerFactory emf;
    private final SpotifyIDRepository spotifyIDRepository;

    public ArtistRepository(Properties DB_ACCESS) {
        emf = Persistence.createEntityManagerFactory(DB_ACCESS.getProperty("persistenceUnitName"), DB_ACCESS);
        spotifyIDRepository = new SpotifyIDRepository(DB_ACCESS);
    }

    /**
     * Get count of artists in the database.
     * @return count of genres in the database.
     */
    public long count() {
        try (var entityManager = emf.createEntityManager()) {
            return (Long) entityManager.createNamedQuery("Artist.countBy").getSingleResult();
        }
    }

    /**
     * Find Artist by spotifyID field.
     * @param apiArtist Artist object generated by the spotify-web-api.
     * @return Artist if apiArtist already exists in the database.
     */
    public Optional<Artist> find(@NonNull se.michaelthelin.spotify.model_objects.specification.Artist apiArtist) {
        return find(apiArtist.getId());
    }

    /**
     * Find Artist by Spotify ID string value.
     * @param id String containing a Spotify ID.
     * @return Artist if id matches the spotify_id field in the table and not blank.
     */
    public Optional<Artist> find(@NonNull String id) {
        try (var entityManager = emf.createEntityManager()) {
            var query = entityManager.createNamedQuery("Artist.findBySpotifyID", Artist.class);
            final var optionalSpotifyID = spotifyIDRepository.find(id);
            if (optionalSpotifyID.isEmpty()) {
                return Optional.empty();
            } else {
                query.setParameter("spotifyID", optionalSpotifyID.get());
                try {
                    return Optional.of(query.getSingleResult());
                } catch (NoResultException e) {
                    return Optional.empty();
                }
            }
        }
    }

    /**
     * Check if Artist exists in the database.
     * @param artist Artist to check
     * @return true if artist exists in the database.
     */
    public boolean exists(@NonNull Artist artist) {
        try (var entityManager = emf.createEntityManager()) {
            return entityManager.find(Artist.class, artist.getId()) != null;
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    /**
     * Checks if Artist object generated by the spotify-web-api exists in the database.
     * @param apiArtist Artist object generated by the spotify-web-api.
     * @return true if apiArtist exists in the database.
     */
    public boolean exists(@NonNull se.michaelthelin.spotify.model_objects.specification.Artist apiArtist) {
        return find(apiArtist).isPresent();
    }

    /**
     * Check if Artist exists in persistence context by Spotify ID string value.
     * @param id String containing a Spotify ID.
     * @return true if Artist specified by id exists in the database.
     */
    public boolean exists(@NonNull String id) {
        return find(id).isPresent();
    }

    /**
     * Converts Image[] generated by spotify-web-api to Set<SpotifyImage>.
     */
    private Set<SpotifyImage> imageSetFactory(@NonNull Image[] images) {
        Set<SpotifyImage> imageSet = new HashSet<>();
        for (var image : images) {
            var newSpotifyImage = SpotifyImage.builder()
                    .url(image.getUrl())
                    .width(image.getWidth())
                    .height(image.getHeight())
                    .build();
            imageSet.add(newSpotifyImage);
        }
        return imageSet;
    }

    /**
     * Converts genreNames[] generated by spotify-web-api to Set<Genre> and updates link table for ManyToMany mapping.
     */
    private Set<Genre> genreSetFactory(EntityManager entityManager, @NonNull String[] genreNames) {
        if (!entityManager.getTransaction().isActive()) {
            throw new RuntimeException("Method will only work from within an active transaction.");
        }
        Set<Genre> genreSet = new HashSet<>();
        for (var genreName : genreNames) {
            var query = entityManager.createNamedQuery("Genre.findByName", Genre.class);
            query.setParameter("name", genreName);
            try {
                genreSet.add(query.getSingleResult());
            } catch (NoResultException e) {
                genreSet.add(new Genre(genreName.toLowerCase(Locale.ENGLISH)));
            }
        }
        for (var genre : genreSet) {
            entityManager.persist(genre);
        }
        return genreSet;
    }

    /**
     * Attempts to persist an Artist from the output of the spotify-web-api.
     * @param apiArtist Artist object generated by the spotify-web-api.
     * @return Artist if already in the database or if apiArtist has a new Spotify ID.
     */
    public Optional<Artist> persist(@NonNull se.michaelthelin.spotify.model_objects.specification.Artist apiArtist) {
        var optionalArtist = find(apiArtist);
        if (optionalArtist.isPresent()) {
            return optionalArtist;
        } else {
            var newArtist = Artist.builder()
                    .name(apiArtist.getName())
                    .spotifyID(new SpotifyID(apiArtist.getId()))
                    .build();
            try (var entityManager = emf.createEntityManager()) {
                entityManager.getTransaction().begin();
                newArtist.addImages(imageSetFactory(apiArtist.getImages()));
                newArtist.addGenres(genreSetFactory(entityManager, apiArtist.getGenres()));
                entityManager.persist(newArtist);
                entityManager.getTransaction().commit();
                return Optional.of(newArtist);
            }
        }
    }

    /**
     * Attempts to persist an array of Artist objects from the output of the spotify-web-api.
     * @param apiArtists An array of Artist objects generated by the spotify-web-api.
     * @return Set of Artist objects.
     */
    public Set<Artist> persistAll(@NonNull se.michaelthelin.spotify.model_objects.specification.Artist[] apiArtists) {
        Set<Artist> artistSet = new HashSet<>();
        for (var apiArtist : apiArtists) {
            var artist = persist(apiArtist);
            artist.ifPresent(artistSet::add);
        }
        return artistSet;
    }
}
